version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5050:5050
    networks:
      - postgres
    restart: always
    depends_on:
      - postgres

  redis:
    image: redis:6.0.7
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: ['redis-server', '/redis.conf']

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
