export const FETCH_COMPONENT_REQUEST = 'FETCH_COMPONENT_REQUEST';
export const FETCH_COMPONENT_SUCCESS = 'FETCH_COMPONENT_SUCCESS';
export const FETCH_COMPONENT_FAILURE = 'FETCH_COMPONENT_FAILURE';

export const ADD_CPU_TO_SETUP = 'ADD_CPU_TO_SETUP';
export const ADD_GPU_TO_SETUP = 'ADD_GPU_TO_SETUP';
export const ADD_RAM_TO_SETUP = 'ADD_RAM_TO_SETUP';
export const ADD_MOTHERBOARD_TO_SETUP = 'ADD_MOTHERBOARD_TO_SETUP';
export const ADD_POWERSUPPLY_TO_SETUP = 'ADD_POWERSUPPLY_TO_SETUP';

export const ADD_COMPONENT_TO_SETUP = 'ADD_COMPONENT_TO_SETUP';

export const REMOVE_CPU_FROM_SETUP = 'REMOVE_CPU_FROM_SETUP';
export const REMOVE_GPU_FROM_SETUP = 'REMOVE_GPU_FROM_SETUP';
export const REMOVE_RAM_FROM_SETUP = 'REMOVE_RAM_FROM_SETUP';
export const REMOVE_MOTHERBOARD_FROM_SETUP = 'REMOVE_MOTHERBOARD_FROM_SETUP';
export const REMOVE_POWERSUPPLY_FROM_SETUP = 'REMOVE_POWERSUPPLY_FROM_SETUP';

export const REMOVE_COMPONENT_FROM_SETUP = 'REMOVE_COMPONENT_FROM_SETUP';

export const INIT_SETUP = 'INIT_SETUP';
export const RESET_SETUP = 'RESET_SETUP';
export const SET_SETUP = 'SET_SETUP';
