export const FETCH_CPU_REQUEST = 'FETCH_CPU_REQUEST';
export const FETCH_CPU_SUCCESS = 'FETCH_CPU_SUCCESS';
export const FETCH_CPU_FAILURE = 'FETCH_CPU_FAILURE';
export const FETCH_GPU_REQUEST = 'FETCH_GPU_REQUEST';
export const FETCH_GPU_SUCCESS = 'FETCH_GPU_SUCCESS';
export const FETCH_GPU_FAILURE = 'FETCH_GPU_FAILURE';
export const FETCH_RAM_REQUEST = 'FETCH_RAM_REQUEST';
export const FETCH_RAM_SUCCESS = 'FETCH_RAM_SUCCESS';
export const FETCH_RAM_FAILURE = 'FETCH_RAM_FAILURE';
export const FETCH_MOTHERBOARD_REQUEST = 'FETCH_MOTHERBOARD_REQUEST';
export const FETCH_MOTHERBOARD_SUCCESS = 'FETCH_MOTHERBOARD_SUCCESS';
export const FETCH_MOTHERBOARD_FAILURE = 'FETCH_MOTHERBOARD_FAILURE';
export const FETCH_POWERSUPPLY_REQUEST = 'FETCH_POWERSUPPLY_REQUEST';
export const FETCH_POWERSUPPLY_SUCCESS = 'FETCH_POWERSUPPLY_SUCCESS';
export const FETCH_POWERSUPPLY_FAILURE = 'FETCH_POWERSUPPLY_FAILURE';

export const ADD_CPU_TO_SETUP = 'ADD_CPU_TO_SETUP';
export const ADD_GPU_TO_SETUP = 'ADD_GPU_TO_SETUP';
export const ADD_RAM_TO_SETUP = 'ADD_RAM_TO_SETUP';
export const ADD_MOTHERBOARD_TO_SETUP = 'ADD_MOTHERBOARD_TO_SETUP';
export const ADD_POWERSUPPLY_TO_SETUP = 'ADD_POWERSUPPLY_TO_SETUP';

export const REMOVE_CPU_FROM_SETUP = 'REMOVE_CPU_FROM_SETUP';
export const REMOVE_GPU_FROM_SETUP = 'REMOVE_GPU_FROM_SETUP';
export const REMOVE_RAM_FROM_SETUP = 'REMOVE_RAM_FROM_SETUP';
export const REMOVE_MOTHERBOARD_FROM_SETUP = 'REMOVE_MOTHERBOARD_FROM_SETUP';
export const REMOVE_POWERSUPPLY_FROM_SETUP = 'REMOVE_POWERSUPPLY_FROM_SETUP';

export const RESET_SETUP = 'RESET_SETUP';
