export const FETCH_COMPONENT_REQUEST = 'FETCH_COMPONENT_REQUEST';
export const FETCH_COMPONENT_SUCCESS = 'FETCH_COMPONENT_SUCCESS';
export const FETCH_COMPONENT_FAILURE = 'FETCH_COMPONENT_FAILURE';

export const ADD_COMPONENT_TO_SETUP = 'ADD_COMPONENT_TO_SETUP';
export const REMOVE_COMPONENT_FROM_SETUP = 'REMOVE_COMPONENT_FROM_SETUP';

export const BUILDER_INIT_SETUP = 'BUILDER_INIT_SETUP';
export const BUILDER_RESET_SETUP = 'BUILDER_RESET_SETUP';
export const BUILDER_SET_SETUP = 'BUILDER_SET_SETUP';
