enum HardwareFields {
  perfomance = 'Perfomance',
  tdp = 'TDP',
  socket = 'Socket',
  clockSpeed = 'Clock Speed',
  cores = 'Cores',
  classCpu = 'Class',
  interfaceGpu = 'Interface',
  memorySize = 'Memory Size',
  coreClocks = 'Core Clocks',
  directX = 'DirectX',
  openGL = 'OpenGL',
  ram = 'RAM',
  power = 'Power',
  frequency = 'Frequency',
  typeRam = 'Type',
  sata = 'Sata',
  m2 = 'M2',
  capacity = 'Capacity',
  size = 'Size',
  rpm = 'RPM',
  ramValue = 'RAMValue',
}

export { HardwareFields };
